s = open('../../.svn/entries', 'r')
s.readline()
s.readline()
s.readline()
svn_revision = s.readline()
s.readline()
s.readline()
s.readline()
s.readline()
s.readline()
svn_date = s.readline()
s.close()

f = open('svn.cpp', 'w')
f.write('#include "svn.h"\n')
f.write('const unsigned int SVN_REVISION = ' + svn_revision.strip() + ';\n')
f.write('const char SVN_DATE[255] = "' + svn_date.strip() + '";\n')
f.close()
