import sys

Help("""
Build the Steel Engine: 'scons mode=... uses=...`
Clear the built Steel Engine: 'scons -c`

========
Build mode: debug|release; default: debug
	'debug`: build debug version, debug mode can be set
	'release`: build the release version

Using feachures: gettext; default: gettext
	'gettext`: enable the support of GETTEXT library
	""")

env=Environment(CPPPATH=["/usr/include/SDL"], CCFLAGS="-Wall -DSTEEL_COMPILER=0 -DSTEEL_OPENGL_API=0 -DSTEEL_OS=0")

mode=ARGUMENTS.get("mode","debug")
if mode=="debug":
	env.Append(CCFLAGS=" -g -DDEBUG")
elif mode=="release":
	env.Append(CCFLAGS=" -O3")
	env.Append(LINKFLAGS=" -s")
else:
	print "Invalid mode ( debug|release )"
	sys.exit()

uses=ARGUMENTS.get("uses","gettext")
if "gettext" in uses:
	env.Append(CCFLAGS=" -DSTEEL_USE_GETTEXT")

sources = Split("""
	./interface.cpp
	./steel.cpp
	./math/line.cpp
	./math/plane.cpp
	./math/maths.cpp
	./math/aabb.cpp
	./math/matrix34.cpp
	./math/matrix33.cpp
	./math/vector2d.cpp
	./math/vector3d.cpp
	./game/game.cpp
	./input/input_sdl.cpp
	./input/input_win.cpp
	./input/input.cpp
	./common/steel_vector.cpp
	./common/logger.cpp
	./common/utils.cpp
	./common/timer.cpp
	./common/system_info.cpp
	./common/win_info.cpp
	./graph/graph_helper.cpp
	./graph/graph_engine.cpp
	./graph/opengl/opengl_sdl_engine.cpp
	./graph/opengl/extensions.cpp
	./graph/opengl/ext/normalisation_cube_map.cpp
	./graph/opengl/opengl_engine.cpp
	./graph/opengl/gl/libext.cpp
	./graph/opengl/opengl_win_engine.cpp
	./graph/opengl/opengl_10.cpp
	./graph/opengl/opengl_11.cpp
	./graph/opengl/opengl_13.cpp
	./graph/opengl/opengl_15.cpp
	./graph/opengl/opengl_20.cpp
	./graph/opengl/opengl_glsl.cpp
	./test.cpp
	./objects/custom_path.cpp
	./objects/game_obj.cpp
	./objects/ps/ps_renderer.cpp
	./objects/ps/animator.cpp
	./objects/ps/emitter.cpp
	./objects/ps/particle_system.cpp
	./objects/group.cpp
	./objects/triangle.cpp
	./objects/model_obj.cpp
	./objects/path.cpp
	./objects/combiner.cpp
	./objects/sphere.cpp
	./res/rstream.cpp
	./res/res_main.cpp
	./res/conf/conf.cpp
	./res/conf/conf_text.cpp
	./res/model/_3ds.cpp
	./res/model/lightwave.cpp
	./res/model/model.cpp
	./res/model/bones.cpp
	./res/material/material.cpp
	./res/script/script.cpp
	./res/script/script_text.cpp
	./res/res.cpp
	./res/image/image.cpp
	./res/image/bmp.cpp
	./res/image/png.cpp
	./res/image/tga.cpp
	./res/text/text_file.cpp
	./physic/physic_engine.cpp
	./physic/physic_engine_steel.cpp
	./physic/pe_particle.cpp
	./main.cpp
	""")

libs = Split("""
	SDL
	GL
	glut
	png
	""")

libpaths = Split("""
	""")

steel=env.Program("steel",sources,LIBS=libs,LIBPATH=libpaths)
Default(steel)
